### ISSUE TITLE
The charset attribute on the script element is obsolete.

### ISSUE THREAD

**Issue by GrosSacASac** [luxembourgjs/luxembourgjs.github.io#3]
It should be discarded. HTTP already defines a way to declare encoding.
https://github.com/luxembourgjs/luxembourgjs.github.io/blob/master/index.html#L93

**Comment by thomaswinckell** [comment]
I think this was generated by twitter. Maybe for backward compatibility ? If there's no reason, we can remove it.

**Comment by biou** [comment]
agree, it's just the embed code directly copy-pasted from twitter. Feel
free to remove this.
